# Generated by Django 5.2 on 2025-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('type', models.CharField(max_length=50, verbose_name='Тип работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Состав работников',
            },
        ),
    ]
