# Generated by Django 5.1.7 on 2025-04-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carservicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на сервис', 'verbose_name_plural': 'Заявки на сервис'},
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='problem_description',
            field=models.TextField(default='Не указано', max_length=100, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обслуживания'),
        ),
        migrations.AddField(
            model_name='carservicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
